sudo: required
dist: trusty
language: node_js
node_js:
- '6.10'
install:
- npm install
before_script:
- grunt test
script:
- npm run test
deploy:
  provider: npm
  email: john.capehart@organicvalley.coop
  api_key:
    secure: hZ2tX0KyreaYgzF13QeQqFOh2zlWf1RrIGpsWDyo8EPTLjmPgeXEt32a9dv21SeWJAn7QCD0Hdd3n7Exin22mLH04FoCpd2A9ZrJaoeKTtZvq2jNSMr/5E+wUfL86DCwS1Ygjdby6UjF87//3EWX+vAiKqItQZ0H0fNJtmrnitGg2WhTPVKfUK9/JiY+Gc0mz0PDq/ZFLbzhI5g//+MOwAp5m4zfnTKM8unwrCXI7KVyag1tJB/Q9PMXBtZBSHYdgsMMAb74CNOkgadQu/+dM4pt4y72b+9hMJXEcj5IqVDJw8LV4mwJtyLb0PL0lbSsbmZFnju1fG+u0TymZ7uMqBJEXcyv1LksmR8f90Bv+4TaaeMSMZt3w5rRpzfR1Z70Cv60BZGpfbuj7e2H3KvXjsoKbMWi5zGQry8ST7quS2cYFOEHN7HGKSoAuEYpt23Zpu8n9l0iD9RmvBdWVwLOZl/WJHrgoNBTlSaPyS5A+amA0H2jX3oGOZjPCEcbCsekdKm16ZQAV6VVQxndst2QBIxW3BO0J3ACwFvADAwqFpsEpfWl3z0r5w6YICyDywotFwXB8Lw4OZLWt2JawxyGGMZJ5cayh9Du7NQkFjz0OFs2KPDYzT6Nn1VVIcayamJVWqIJiHxUSauf4VRVaeqqJBaYUCN0hwNPHMoef7iET34=
  on:
    repo: johncapehart/progressive-config
    branch: develop
